name: Deploy frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [ test/main ]

env:
  SPA_LOCATION: 'src/Pjfm.Bff/ClientApp'
  BFF_LOCATION: 'src/Pjfm.Bff'
  BUILD_CONFIGURATION: 'Release'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.SPA_LOCATION }}
      - name: Build ClientApp
        run: npm build
        working-directory: ${{ env.SPA_LOCATION }}
      - name: Use Dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore Bff
        run: dotnet restore
        working-directory: ${{ env.BFF_LOCATION }}
      - name: Build Bff
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
        working-directory: ${{ env.BFF_LOCATION }}
      - name: Publish Frontend
        run: dotnet publish --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --output publish/out
        working-directory: ${{ env.BFF_LOCATION }}
      
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
         docker build ${{ env.BFF_LOCATION }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/polderjongensfm:${{ github.sha }}        
         docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/polderjongensfm:${{ github.sha }}
         
      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/polderjongensfm:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aci-polderjongensfm
          location: west europe
