name: Deploy frontend

on:
  push:
    branches: [ test/main ]
  pull_request:
    branches: [ test/main ]

env:
  frontendLocation: 'src/Pjfm.Bff/ClientApp'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.frontendLocation }}