name: Deploy frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [ test/main ]

env:
  frontendLocation: 'src/Pjfm.Bff/ClientApp'
  bffLocation: 'src/Pjfm.Bff'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x.x'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.frontendLocation }}
      - name: Build ClientApp
        run: npm build
        working-directory: ${{  env.frontendLocation }}
      - name: Use Dotnet SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore Bff
        run: dotnet restore
        working-directory: ${{ env.bffLocation }}
      - name: Build Bff
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{ env.bffLocation }}
      - name: Publish Frontend
        run: dotnet publish --no-build --configuration Release --output publish/out
        
